version: '3'
services:
  web:
    build: "~/Imaya/image_folder/image_config_web" 
    ports:
      - "5000:5000"

  mysql:
    build:
        context: "/home/kannank/Imaya/image_folder/mysql/"

    environment: 
      MYSQL_DATABASE: "feedback_db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
        - "3306:3306"